# Dependencies
markdown:         gfm
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Remyie
tagline:          ''
description:      ''
url:              https://remyie.github.io/remy
baseurl:          https://remyie.github.io/remy

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          

github:
  repo:           
plugins:
  - jekyll-sitemap
